### PR TITLE
fix: remove Next.js runtime

### LINKED ISSUE #108: 500 error on demo site and site from the template
Go to the demo site to reproduce:
https://bejamas-nextjs-blog.netlify.app/

Or [create a new site from the template](https://app.netlify.com/start-with-template) to reproduce in a new site.

cc @MarcL

### PR DESCRIPTION
**Pull request by MarcL**
- Remove dependency on Next.js runtime so the latest version will be automatically installed at build time

Closes #108.

### CODE REVIEW

**Comment by ascorbic** [comment]
How about we just don't manually install it?

**Comment by MarcL** [comment]
🤦🏻 Good shout @ascorbic.

**Comment by verythorough** [comment]
Works for me! Thanks @MarcL!

**Review by orinokai — CHANGES_REQUESTED** [review]
[boulder] package changes all look good, but the plugin also needs to be excised from the toml file

**Review by orinokai — APPROVED** [review]
LGTM 🚀

**Pull request merged**
